set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m4)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(ARM_NONE_EABI_PREFIX arm-none-eabi)

set(CMAKE_C_COMPILER ${ARM_NONE_EABI_PREFIX}-gcc)
set(CMAKE_ASM_COMPILER ${ARM_NONE_EABI_PREFIX}-gcc)
set(CMAKE_AR ${ARM_NONE_EABI_PREFIX}-ar)
set(CMAKE_RANLIB ${ARM_NONE_EABI_PREFIX}-ranlib)
set(CMAKE_OBJCOPY ${ARM_NONE_EABI_PREFIX}-objcopy)
set(CMAKE_SIZE ${ARM_NONE_EABI_PREFIX}-size)

set(CMAKE_C_FLAGS_INIT "-mcpu=cortex-m4 -mthumb -ffunction-sections -fdata-sections")
